# Generated by Django 5.2.17 on 2026-09-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquehorario',
            options={'ordering': ['fecha', 'dia_semana', 'hora_inicio'], 'verbose_name': 'bloque de atención', 'verbose_name_plural': 'bloques de atención'},
        ),
        migrations.RemoveConstraint(
            model_name='bloquehorario',
            name='agenda_bloque_unico_por_dia_y_hora',
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='confirmacion_automatica',
            field=models.BooleanField(blank=True, null=True, verbose_name='confirmación automática'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='duracion_minutos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duración de cada visita en minutos'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha puntual'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='nombre',
            field=models.CharField(blank=True, help_text='Visible para el comprador, por ejemplo «Atención mayoristas».', max_length=80, verbose_name='nombre del bloque'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='visitas_simultaneas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='visitas simultáneas'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='día de la semana'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.UniqueConstraint(condition=models.Q(('dia_semana__isnull', False)), fields=('tienda', 'dia_semana', 'hora_inicio'), name='agenda_bloque_semanal_unico'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha__isnull', False)), fields=('tienda', 'fecha', 'hora_inicio'), name='agenda_bloque_puntual_unico'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dia_semana__isnull', False), ('fecha__isnull', True)), models.Q(('dia_semana__isnull', True), ('fecha__isnull', False)), _connector='OR'), name='agenda_bloque_semanal_o_puntual'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_minutos__isnull', True), ('duracion_minutos__gt', 0), _connector='OR'), name='agenda_bloque_duracion_positiva'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.CheckConstraint(condition=models.Q(('visitas_simultaneas__isnull', True), ('visitas_simultaneas__gt', 0), _connector='OR'), name='agenda_bloque_capacidad_positiva'),
        ),
    ]
