# Generated by Django 5.2.17 on 2026-09-26 20:06

import apps.usuarios.models
import apps.usuarios.validadores
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('rut', models.CharField(blank=True, help_text='Formato 12345678-5, sin puntos.', max_length=12, null=True, unique=True, validators=[apps.usuarios.validadores.validar_rut], verbose_name='RUT')),
                ('rol', models.CharField(choices=[('admin_plataforma', 'Administrador de plataforma'), ('dueno_tienda', 'Dueño de tienda'), ('vendedor', 'Vendedor'), ('comprador', 'Comprador')], max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='puede entrar al panel de Django')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='tiendas.tienda', verbose_name='tienda')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('rol__in', ('dueno_tienda', 'vendedor')), ('tienda__isnull', False)), models.Q(('rol__in', ('admin_plataforma', 'comprador')), ('tienda__isnull', True)), _connector='OR'), name='usuario_tienda_segun_rol')],
            },
            managers=[
                ('objects', apps.usuarios.models.GestorDeUsuarios()),
            ],
        ),
    ]
