--
-- PostgreSQL database dump
--

\restrict nNd1bDDyxuoIuIASAbxckN2QiWoOd7hrsLmoQQK8oZhKAlAWfs5e8IL1G4A4a5C

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agenda_bloquehorario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_bloquehorario (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_edicion timestamp with time zone NOT NULL,
    dia_semana integer,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    tienda_id bigint NOT NULL,
    confirmacion_automatica boolean,
    duracion_minutos smallint,
    fecha date,
    nombre character varying(80) NOT NULL,
    visitas_simultaneas smallint,
    CONSTRAINT agenda_bloque_capacidad_positiva CHECK (((visitas_simultaneas IS NULL) OR (visitas_simultaneas > 0))),
    CONSTRAINT agenda_bloque_duracion_positiva CHECK (((duracion_minutos IS NULL) OR (duracion_minutos > 0))),
    CONSTRAINT agenda_bloque_semanal_o_puntual CHECK ((((dia_semana IS NOT NULL) AND (fecha IS NULL)) OR ((dia_semana IS NULL) AND (fecha IS NOT NULL)))),
    CONSTRAINT agenda_bloque_termina_despues_de_empezar CHECK ((hora_fin > hora_inicio)),
    CONSTRAINT agenda_bloquehorario_duracion_minutos_check CHECK ((duracion_minutos >= 0)),
    CONSTRAINT agenda_bloquehorario_visitas_simultaneas_check CHECK ((visitas_simultaneas >= 0))
);


--
-- Name: agenda_bloquehorario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agenda_bloquehorario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agenda_bloquehorario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agenda_configuracionagenda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_configuracionagenda (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_edicion timestamp with time zone NOT NULL,
    duracion_minutos smallint NOT NULL,
    visitas_por_bloque smallint NOT NULL,
    anticipacion_minima_horas smallint NOT NULL,
    ventana_maxima_dias smallint NOT NULL,
    confirmacion_automatica boolean NOT NULL,
    direccion character varying(250) NOT NULL,
    indicaciones text NOT NULL,
    correo_notificaciones character varying(254) NOT NULL,
    token_feed character varying(64) NOT NULL,
    tienda_id bigint NOT NULL,
    CONSTRAINT agenda_capacidad_positiva CHECK ((visitas_por_bloque > 0)),
    CONSTRAINT agenda_configuracionagenda_anticipacion_minima_horas_check CHECK ((anticipacion_minima_horas >= 0)),
    CONSTRAINT agenda_configuracionagenda_duracion_minutos_check CHECK ((duracion_minutos >= 0)),
    CONSTRAINT agenda_configuracionagenda_ventana_maxima_dias_check CHECK ((ventana_maxima_dias >= 0)),
    CONSTRAINT agenda_configuracionagenda_visitas_por_bloque_check CHECK ((visitas_por_bloque >= 0)),
    CONSTRAINT agenda_duracion_positiva CHECK ((duracion_minutos > 0))
);


--
-- Name: agenda_configuracionagenda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agenda_configuracionagenda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agenda_configuracionagenda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agenda_diabloqueado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_diabloqueado (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_edicion timestamp with time zone NOT NULL,
    fecha date NOT NULL,
    motivo character varying(150) NOT NULL,
    tienda_id bigint NOT NULL
);


--
-- Name: agenda_diabloqueado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agenda_diabloqueado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agenda_diabloqueado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agenda_enviocorreo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_enviocorreo (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_edicion timestamp with time zone NOT NULL,
    tipo character varying(30) NOT NULL,
    destinatario character varying(254) NOT NULL,
    estado character varying(20) NOT NULL,
    intentos smallint NOT NULL,
    ultimo_error text NOT NULL,
    enviado_en timestamp with time zone,
    tienda_id bigint NOT NULL,
    visita_id bigint NOT NULL,
    CONSTRAINT agenda_enviocorreo_intentos_check CHECK ((intentos >= 0))
);


--
-- Name: agenda_enviocorreo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agenda_enviocorreo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agenda_enviocorreo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agenda_visita; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_visita (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_edicion timestamp with time zone NOT NULL,
    uid uuid NOT NULL,
    inicio timestamp with time zone NOT NULL,
    fin timestamp with time zone NOT NULL,
    posicion smallint NOT NULL,
    estado character varying(20) NOT NULL,
    nombre_contacto character varying(150) NOT NULL,
    correo_contacto character varying(254) NOT NULL,
    telefono_contacto character varying(30) NOT NULL,
    motivo text NOT NULL,
    motivo_rechazo text NOT NULL,
    secuencia integer NOT NULL,
    recordatorio_enviado_en timestamp with time zone,
    comprador_id bigint NOT NULL,
    tienda_id bigint NOT NULL,
    CONSTRAINT agenda_visita_posicion_check CHECK ((posicion >= 0)),
    CONSTRAINT agenda_visita_secuencia_check CHECK ((secuencia >= 0)),
    CONSTRAINT agenda_visita_termina_despues_de_empezar CHECK ((fin > inicio))
);


--
-- Name: agenda_visita_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agenda_visita ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agenda_visita_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_aprobacionmayorista; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes_aprobacionmayorista (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_edicion timestamp with time zone NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_resolucion timestamp with time zone,
    comprador_id bigint NOT NULL,
    resuelta_por_id bigint,
    tienda_id bigint NOT NULL
);


--
-- Name: clientes_aprobacionmayorista_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clientes_aprobacionmayorista ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_aprobacionmayorista_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: tiendas_solicituddeacceso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiendas_solicituddeacceso (
    id bigint NOT NULL,
    negocio character varying(150) NOT NULL,
    nombre character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    telefono character varying(30) NOT NULL,
    mensaje text NOT NULL,
    estado character varying(20) NOT NULL,
    notas text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL
);


--
-- Name: tiendas_solicituddeacceso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tiendas_solicituddeacceso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tiendas_solicituddeacceso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tiendas_tienda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiendas_tienda (
    id bigint NOT NULL,
    slug character varying(60) NOT NULL,
    nombre character varying(120) NOT NULL,
    activa boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    banner character varying(100),
    color_acento character varying(7) NOT NULL,
    color_destacado character varying(7) NOT NULL,
    color_primario character varying(7) NOT NULL,
    color_primario_hover character varying(7) NOT NULL,
    instagram character varying(200) NOT NULL,
    logo character varying(100),
    whatsapp character varying(200) NOT NULL
);


--
-- Name: tiendas_tienda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tiendas_tienda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tiendas_tienda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    nombre character varying(150) NOT NULL,
    rut character varying(12),
    rol character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    tienda_id bigint,
    CONSTRAINT usuario_tienda_segun_rol CHECK (((((rol)::text = ANY ((ARRAY['dueno_tienda'::character varying, 'vendedor'::character varying])::text[])) AND (tienda_id IS NOT NULL)) OR (((rol)::text = ANY ((ARRAY['admin_plataforma'::character varying, 'comprador'::character varying])::text[])) AND (tienda_id IS NULL))))
);


--
-- Name: usuarios_usuario_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agenda_bloquehorario agenda_bloquehorario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_bloquehorario
    ADD CONSTRAINT agenda_bloquehorario_pkey PRIMARY KEY (id);


--
-- Name: agenda_configuracionagenda agenda_configuracionagenda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_configuracionagenda
    ADD CONSTRAINT agenda_configuracionagenda_pkey PRIMARY KEY (id);


--
-- Name: agenda_configuracionagenda agenda_configuracionagenda_token_feed_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_configuracionagenda
    ADD CONSTRAINT agenda_configuracionagenda_token_feed_key UNIQUE (token_feed);


--
-- Name: agenda_diabloqueado agenda_dia_bloqueado_unico; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_diabloqueado
    ADD CONSTRAINT agenda_dia_bloqueado_unico UNIQUE (tienda_id, fecha);


--
-- Name: agenda_diabloqueado agenda_diabloqueado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_diabloqueado
    ADD CONSTRAINT agenda_diabloqueado_pkey PRIMARY KEY (id);


--
-- Name: agenda_enviocorreo agenda_enviocorreo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_enviocorreo
    ADD CONSTRAINT agenda_enviocorreo_pkey PRIMARY KEY (id);


--
-- Name: agenda_configuracionagenda agenda_una_configuracion_por_tienda; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_configuracionagenda
    ADD CONSTRAINT agenda_una_configuracion_por_tienda UNIQUE (tienda_id);


--
-- Name: agenda_visita agenda_visita_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_visita
    ADD CONSTRAINT agenda_visita_pkey PRIMARY KEY (id);


--
-- Name: agenda_visita agenda_visita_uid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_visita
    ADD CONSTRAINT agenda_visita_uid_key UNIQUE (uid);


--
-- Name: clientes_aprobacionmayorista aprobacion_unica_por_tienda_y_comprador; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes_aprobacionmayorista
    ADD CONSTRAINT aprobacion_unica_por_tienda_y_comprador UNIQUE (tienda_id, comprador_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: clientes_aprobacionmayorista clientes_aprobacionmayorista_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes_aprobacionmayorista
    ADD CONSTRAINT clientes_aprobacionmayorista_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: tiendas_solicituddeacceso tiendas_solicituddeacceso_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiendas_solicituddeacceso
    ADD CONSTRAINT tiendas_solicituddeacceso_email_key UNIQUE (email);


--
-- Name: tiendas_solicituddeacceso tiendas_solicituddeacceso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiendas_solicituddeacceso
    ADD CONSTRAINT tiendas_solicituddeacceso_pkey PRIMARY KEY (id);


--
-- Name: tiendas_tienda tiendas_tienda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiendas_tienda
    ADD CONSTRAINT tiendas_tienda_pkey PRIMARY KEY (id);


--
-- Name: tiendas_tienda tiendas_tienda_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiendas_tienda
    ADD CONSTRAINT tiendas_tienda_slug_key UNIQUE (slug);


--
-- Name: usuarios_usuario usuarios_usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_email_key UNIQUE (email);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq UNIQUE (usuario_id, group_id);


--
-- Name: usuarios_usuario usuarios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_rut_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_rut_key UNIQUE (rut);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: agenda_asiento_unico_por_bloque; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agenda_asiento_unico_por_bloque ON public.agenda_visita USING btree (tienda_id, inicio, posicion) WHERE ((estado)::text = ANY ((ARRAY['solicitada'::character varying, 'confirmada'::character varying, 'asistida'::character varying, 'no_asistio'::character varying])::text[]));


--
-- Name: agenda_bloq_tienda__db20a1_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_bloq_tienda__db20a1_idx ON public.agenda_bloquehorario USING btree (tienda_id);


--
-- Name: agenda_bloque_puntual_unico; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agenda_bloque_puntual_unico ON public.agenda_bloquehorario USING btree (tienda_id, fecha, hora_inicio) WHERE (fecha IS NOT NULL);


--
-- Name: agenda_bloque_semanal_unico; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agenda_bloque_semanal_unico ON public.agenda_bloquehorario USING btree (tienda_id, dia_semana, hora_inicio) WHERE (dia_semana IS NOT NULL);


--
-- Name: agenda_bloquehorario_tienda_id_a58b420a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_bloquehorario_tienda_id_a58b420a ON public.agenda_bloquehorario USING btree (tienda_id);


--
-- Name: agenda_conf_tienda__d701b9_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_conf_tienda__d701b9_idx ON public.agenda_configuracionagenda USING btree (tienda_id);


--
-- Name: agenda_configuracionagenda_tienda_id_4527ec8f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_configuracionagenda_tienda_id_4527ec8f ON public.agenda_configuracionagenda USING btree (tienda_id);


--
-- Name: agenda_configuracionagenda_token_feed_4528411d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_configuracionagenda_token_feed_4528411d_like ON public.agenda_configuracionagenda USING btree (token_feed varchar_pattern_ops);


--
-- Name: agenda_diab_tienda__f381db_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_diab_tienda__f381db_idx ON public.agenda_diabloqueado USING btree (tienda_id);


--
-- Name: agenda_diabloqueado_tienda_id_12abb05e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_diabloqueado_tienda_id_12abb05e ON public.agenda_diabloqueado USING btree (tienda_id);


--
-- Name: agenda_envi_estado_37a194_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_envi_estado_37a194_idx ON public.agenda_enviocorreo USING btree (estado);


--
-- Name: agenda_enviocorreo_tienda_id_a0301b73; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_enviocorreo_tienda_id_a0301b73 ON public.agenda_enviocorreo USING btree (tienda_id);


--
-- Name: agenda_enviocorreo_visita_id_dcb9e3ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_enviocorreo_visita_id_dcb9e3ff ON public.agenda_enviocorreo USING btree (visita_id);


--
-- Name: agenda_visi_tienda__d64478_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_visi_tienda__d64478_idx ON public.agenda_visita USING btree (tienda_id, estado);


--
-- Name: agenda_visi_tienda__e3b969_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_visi_tienda__e3b969_idx ON public.agenda_visita USING btree (tienda_id, inicio);


--
-- Name: agenda_visita_comprador_id_a0da4d80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_visita_comprador_id_a0da4d80 ON public.agenda_visita USING btree (comprador_id);


--
-- Name: agenda_visita_tienda_id_56ddb56f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agenda_visita_tienda_id_56ddb56f ON public.agenda_visita USING btree (tienda_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: clientes_ap_tienda__489b97_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clientes_ap_tienda__489b97_idx ON public.clientes_aprobacionmayorista USING btree (tienda_id);


--
-- Name: clientes_aprobacionmayorista_comprador_id_42bf4e33; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clientes_aprobacionmayorista_comprador_id_42bf4e33 ON public.clientes_aprobacionmayorista USING btree (comprador_id);


--
-- Name: clientes_aprobacionmayorista_resuelta_por_id_cd3e053e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clientes_aprobacionmayorista_resuelta_por_id_cd3e053e ON public.clientes_aprobacionmayorista USING btree (resuelta_por_id);


--
-- Name: clientes_aprobacionmayorista_tienda_id_cc4237fb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clientes_aprobacionmayorista_tienda_id_cc4237fb ON public.clientes_aprobacionmayorista USING btree (tienda_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: tiendas_sol_estado_189f75_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tiendas_sol_estado_189f75_idx ON public.tiendas_solicituddeacceso USING btree (estado, fecha_creacion DESC);


--
-- Name: tiendas_solicituddeacceso_email_4863af70_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tiendas_solicituddeacceso_email_4863af70_like ON public.tiendas_solicituddeacceso USING btree (email varchar_pattern_ops);


--
-- Name: tiendas_tienda_slug_3d213a5d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tiendas_tienda_slug_3d213a5d_like ON public.tiendas_tienda USING btree (slug varchar_pattern_ops);


--
-- Name: usuarios_usuario_email_0a82e5f9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_email_0a82e5f9_like ON public.usuarios_usuario USING btree (email varchar_pattern_ops);


--
-- Name: usuarios_usuario_groups_group_id_e77f6dcf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_group_id_e77f6dcf ON public.usuarios_usuario_groups USING btree (group_id);


--
-- Name: usuarios_usuario_groups_usuario_id_7a34077f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_usuario_id_7a34077f ON public.usuarios_usuario_groups USING btree (usuario_id);


--
-- Name: usuarios_usuario_rut_d29aa436_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_rut_d29aa436_like ON public.usuarios_usuario USING btree (rut varchar_pattern_ops);


--
-- Name: usuarios_usuario_tienda_id_0b9c3af8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_tienda_id_0b9c3af8 ON public.usuarios_usuario USING btree (tienda_id);


--
-- Name: usuarios_usuario_user_permissions_permission_id_4e5c0f2f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_permission_id_4e5c0f2f ON public.usuarios_usuario_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuario_user_permissions_usuario_id_60aeea80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_usuario_id_60aeea80 ON public.usuarios_usuario_user_permissions USING btree (usuario_id);


--
-- Name: agenda_bloquehorario agenda_bloquehorario_tienda_id_a58b420a_fk_tiendas_tienda_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_bloquehorario
    ADD CONSTRAINT agenda_bloquehorario_tienda_id_a58b420a_fk_tiendas_tienda_id FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agenda_configuracionagenda agenda_configuracion_tienda_id_4527ec8f_fk_tiendas_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_configuracionagenda
    ADD CONSTRAINT agenda_configuracion_tienda_id_4527ec8f_fk_tiendas_t FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agenda_diabloqueado agenda_diabloqueado_tienda_id_12abb05e_fk_tiendas_tienda_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_diabloqueado
    ADD CONSTRAINT agenda_diabloqueado_tienda_id_12abb05e_fk_tiendas_tienda_id FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agenda_enviocorreo agenda_enviocorreo_tienda_id_a0301b73_fk_tiendas_tienda_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_enviocorreo
    ADD CONSTRAINT agenda_enviocorreo_tienda_id_a0301b73_fk_tiendas_tienda_id FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agenda_enviocorreo agenda_enviocorreo_visita_id_dcb9e3ff_fk_agenda_visita_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_enviocorreo
    ADD CONSTRAINT agenda_enviocorreo_visita_id_dcb9e3ff_fk_agenda_visita_id FOREIGN KEY (visita_id) REFERENCES public.agenda_visita(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agenda_visita agenda_visita_comprador_id_a0da4d80_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_visita
    ADD CONSTRAINT agenda_visita_comprador_id_a0da4d80_fk_usuarios_usuario_id FOREIGN KEY (comprador_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: agenda_visita agenda_visita_tienda_id_56ddb56f_fk_tiendas_tienda_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_visita
    ADD CONSTRAINT agenda_visita_tienda_id_56ddb56f_fk_tiendas_tienda_id FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_aprobacionmayorista clientes_aprobacionm_comprador_id_42bf4e33_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes_aprobacionmayorista
    ADD CONSTRAINT clientes_aprobacionm_comprador_id_42bf4e33_fk_usuarios_ FOREIGN KEY (comprador_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_aprobacionmayorista clientes_aprobacionm_resuelta_por_id_cd3e053e_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes_aprobacionmayorista
    ADD CONSTRAINT clientes_aprobacionm_resuelta_por_id_cd3e053e_fk_usuarios_ FOREIGN KEY (resuelta_por_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_aprobacionmayorista clientes_aprobacionm_tienda_id_cc4237fb_fk_tiendas_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes_aprobacionmayorista
    ADD CONSTRAINT clientes_aprobacionm_tienda_id_cc4237fb_fk_tiendas_t FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id FOREIGN KEY (user_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario usuarios_usuario_tienda_id_0b9c3af8_fk_tiendas_tienda_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_tienda_id_0b9c3af8_fk_tiendas_tienda_id FOREIGN KEY (tienda_id) REFERENCES public.tiendas_tienda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict nNd1bDDyxuoIuIASAbxckN2QiWoOd7hrsLmoQQK8oZhKAlAWfs5e8IL1G4A4a5C

