# Generated by Django 5.2.17 on 2026-09-26 20:21

import apps.agenda.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador de calendario')),
                ('inicio', models.DateTimeField(verbose_name='inicio')),
                ('fin', models.DateTimeField(verbose_name='término')),
                ('posicion', models.PositiveSmallIntegerField(default=0, verbose_name='asiento en el bloque')),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('asistida', 'Asistida'), ('no_asistio', 'No asistió'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20, verbose_name='estado')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='nombre de contacto')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='correo de contacto')),
                ('telefono_contacto', models.CharField(max_length=30, verbose_name='teléfono de contacto')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo de la visita')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='motivo del rechazo')),
                ('secuencia', models.PositiveIntegerField(default=0, verbose_name='secuencia del evento')),
                ('recordatorio_enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='recordatorio enviado en')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to=settings.AUTH_USER_MODEL, verbose_name='comprador')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
                'ordering': ['-inicio'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('tipo', models.CharField(choices=[('solicitud_recibida', 'Solicitud recibida'), ('solicitud_nueva', 'Nueva solicitud para el dueño'), ('confirmada', 'Visita confirmada'), ('rechazada', 'Visita rechazada'), ('reprogramada', 'Visita reprogramada'), ('cancelada', 'Visita cancelada'), ('recordatorio', 'Recordatorio')], max_length=30, verbose_name='tipo')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='estado')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('ultimo_error', models.TextField(blank=True, verbose_name='último error')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tiendas.tienda', verbose_name='tienda')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='agenda.visita', verbose_name='visita')),
            ],
            options={
                'verbose_name': 'envío de correo',
                'verbose_name_plural': 'envíos de correo',
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora de término')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'bloque horario',
                'verbose_name_plural': 'bloques horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'abstract': False,
                'indexes': [models.Index(fields=['tienda'], name='agenda_bloq_tienda__db20a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('tienda', 'dia_semana', 'hora_inicio'), name='agenda_bloque_unico_por_dia_y_hora'), models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='agenda_bloque_termina_despues_de_empezar')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=30, help_text='Con esto se calculan los bloques disponibles.', verbose_name='duración de cada visita en minutos')),
                ('visitas_por_bloque', models.PositiveSmallIntegerField(default=1, verbose_name='visitas simultáneas por bloque')),
                ('anticipacion_minima_horas', models.PositiveSmallIntegerField(default=24, help_text='No se puede pedir hora con menos anticipación que esta.', verbose_name='anticipación mínima en horas')),
                ('ventana_maxima_dias', models.PositiveSmallIntegerField(default=30, help_text='Hasta cuántos días hacia adelante se puede reservar.', verbose_name='ventana máxima en días')),
                ('confirmacion_automatica', models.BooleanField(default=False, help_text='Apagada, cada solicitud espera a que el dueño la acepte.', verbose_name='confirmación automática')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='dirección de la oficina')),
                ('indicaciones', models.TextField(blank=True, verbose_name='cómo llegar')),
                ('correo_notificaciones', models.EmailField(blank=True, max_length=254, verbose_name='correo de notificaciones')),
                ('token_feed', models.CharField(default=apps.agenda.models.generar_token_feed, max_length=64, unique=True, verbose_name='token del feed de calendario')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'configuración de agenda',
                'verbose_name_plural': 'configuraciones de agenda',
                'abstract': False,
                'indexes': [models.Index(fields=['tienda'], name='agenda_conf_tienda__d701b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('tienda',), name='agenda_una_configuracion_por_tienda'), models.CheckConstraint(condition=models.Q(('duracion_minutos__gt', 0)), name='agenda_duracion_positiva'), models.CheckConstraint(condition=models.Q(('visitas_por_bloque__gt', 0)), name='agenda_capacidad_positiva')],
            },
        ),
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('motivo', models.CharField(blank=True, max_length=150, verbose_name='motivo')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'día bloqueado',
                'verbose_name_plural': 'días bloqueados',
                'ordering': ['fecha'],
                'abstract': False,
                'indexes': [models.Index(fields=['tienda'], name='agenda_diab_tienda__f381db_idx')],
                'constraints': [models.UniqueConstraint(fields=('tienda', 'fecha'), name='agenda_dia_bloqueado_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['tienda', 'inicio'], name='agenda_visi_tienda__e3b969_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['tienda', 'estado'], name='agenda_visi_tienda__d64478_idx'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('solicitada', 'confirmada', 'asistida', 'no_asistio'))), fields=('tienda', 'inicio', 'posicion'), name='agenda_asiento_unico_por_bloque'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='agenda_visita_termina_despues_de_empezar'),
        ),
        migrations.AddIndex(
            model_name='enviocorreo',
            index=models.Index(fields=['estado'], name='agenda_envi_estado_37a194_idx'),
        ),
    ]
