# Generated by Django 5.2.17 on 2026-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('estado', models.CharField(choices=[('sin_solicitar', 'Sin solicitar'), ('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='sin_solicitar', max_length=20, verbose_name='estado')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
            ],
            options={
                'verbose_name': 'aprobación mayorista',
                'verbose_name_plural': 'aprobaciones mayoristas',
                'abstract': False,
            },
        ),
    ]
