# Generated by Django 5.2.17 on 2026-09-26 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('tiendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aprobacionmayorista',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_mayoristas', to=settings.AUTH_USER_MODEL, verbose_name='comprador'),
        ),
        migrations.AddField(
            model_name='aprobacionmayorista',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por'),
        ),
        migrations.AddField(
            model_name='aprobacionmayorista',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tiendas.tienda', verbose_name='tienda'),
        ),
        migrations.AddIndex(
            model_name='aprobacionmayorista',
            index=models.Index(fields=['tienda'], name='clientes_ap_tienda__489b97_idx'),
        ),
        migrations.AddConstraint(
            model_name='aprobacionmayorista',
            constraint=models.UniqueConstraint(fields=('tienda', 'comprador'), name='aprobacion_unica_por_tienda_y_comprador'),
        ),
    ]
