# Generated by Django 5.2.17 on 2026-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identificador público')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('activa', models.BooleanField(default=True, help_text='Una tienda inactiva no se muestra al público.', verbose_name='activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'tiendas',
                'ordering': ['nombre'],
            },
        ),
    ]
