# Generated by Django 5.2.17 on 2026-09-27 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/banners/', verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_acento',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(code='color_invalido', message='El color debe ser hexadecimal de seis dígitos, como #7C3AED.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color de acento'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_destacado',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(code='color_invalido', message='El color debe ser hexadecimal de seis dígitos, como #7C3AED.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color destacado'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_primario',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(code='color_invalido', message='El color debe ser hexadecimal de seis dígitos, como #7C3AED.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color primario'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_primario_hover',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(code='color_invalido', message='El color debe ser hexadecimal de seis dígitos, como #7C3AED.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color primario al pasar el mouse'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='enlace de Instagram'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='enlace de WhatsApp'),
        ),
    ]
