# Generated by Django 5.2.17 on 2026-09-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_tienda_banner_tienda_color_acento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=150, verbose_name='nombre del negocio')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre de contacto')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='teléfono o WhatsApp')),
                ('mensaje', models.TextField(blank=True, verbose_name='qué vende')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('activada', 'Activada'), ('descartada', 'Descartada')], default='nueva', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de la solicitud')),
            ],
            options={
                'verbose_name': 'solicitud de acceso',
                'verbose_name_plural': 'solicitudes de acceso',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', '-fecha_creacion'], name='tiendas_sol_estado_189f75_idx')],
            },
        ),
    ]
